// Generated by Haxe TypeScript Declaration Generator :)

export namespace client.data {
	export type IThingProps = {
	}
}

export namespace client.data {
	export interface IReactComponent {
		foo: string;
		title: string;
	}
}

export namespace client.data {
	export class ThingViewModel {
		constructor(reactComponent: client.data.ReactComponent);
		handleChange(e: any): void;
		clickBtn(): void;
	}
}