package client.data;

import coconut.data.Model;

class TodoItemModel implements Model {
  @:editable var completed:Bool = @byDefault false;
  @:editable var description:String;
  @:constant var created:Date = @byDefault Date.now();

  static public function isActive(item: TodoItemModel)
    return !item.completed;

  static public function isCompleted(item: TodoItemModel)
    return item.completed;

  static public function create(description:String) 
    return new TodoItemModel({description: description});//Constructor is autogenerated
}

@:expose
class TodoItemStore {
  public var item: TodoItemModel;
  public var completed: Bool;
  public var description: String;
  public var created: Date;

  public function new(item: TodoItemModel) { 
    this.item = item; 
    this.description = item.description;
    this.created = item.created;
    this.completed = item.completed;
  }

  public static function create(description: String) {
    var item = TodoItemModel.create(description);
    var store = new TodoItemStore(item);
    return store;
  }

  public static function wrap(item: TodoItemModel) {
    var store = new TodoItemStore(item);
    return store;
  }

  public function setCompleted(val: Bool) { this.completed = val; };
  public function setDescription(val: String) { this.description = val; };

  public function isActive() { return TodoItemModel.isActive(this.item); }
  public function isCompleted() { return TodoItemModel.isCompleted(this.item); }
}
