// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delete': string;
  'description': string;
  'todo-item': string;
}
declare const cssExports: CssExports;
export = cssExports;
