// Generated by Haxe TypeScript Declaration Generator :)

export namespace client.data {
	export type IThingProps = {
	}
}

export namespace client.data {
	export type IThingState = {
		result: string;
	}
}

export namespace client.data {
	export interface IReactComponent {
		foo: string;
	}
}

export type Result = {
	slideshow: {author: string, date: string, slides: {items?: string[], title: string, type: string}[], title: string};
}

export namespace client.data {
	export class ThingController {
		constructor(reactComponent: client.data.ReactComponent);
		bare: Result;
		clickBtn(): void;
	}
}