// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mark-all': string;
  'todo-list': string;
}
declare const cssExports: CssExports;
export = cssExports;
